# Generated by Django 5.1.3 on 2024-12-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='subprogram',
            name='created_by',
        ),
    ]
