# Generated by Django 5.1.3 on 2024-12-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='bill',
            field=models.ImageField(blank=True, null=True, upload_to='bills/'),
        ),
        migrations.AddField(
            model_name='program',
            name='aggrement',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
    ]
