# Generated by Django 5.1.3 on 2024-12-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_donation_voucher_expense_bill_program_aggrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='voucher',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bill',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
