# Generated by Django 5.1.3 on 2024-12-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_donor_pan_no_organization_pan_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
