# Generated by Django 5.1.3 on 2024-12-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_alter_organization_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
