# Generated by Django 5.1.3 on 2024-12-10 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_donation_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='aggrement',
            new_name='agreement',
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], default='Individual', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Supplies', 'Supplies'), ('Salaries', 'Salaries'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50),
        ),
        migrations.AddField(
            model_name='exportdetail',
            name='exported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programperformance',
            name='units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programperformance',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
